---
settings:
  name: NetApp data services
  platform: cloud
  search: console-relnotes,console-setup-admin,storage-management-cloud-volumes-ontap,storage-management-ontap-onprem,storage-management-azure-netapp-files,storage-management-fsx-ontap,storage-management-cloud-volumes-service-gcp,data-services-backup-recovery,data-services-copy-sync,data-services-data-classification,data-services-cloud-tiering,data-services-replication,console-automation,cloud-volumes-ontap-relnotes,storage-management-storagegrid,storage-management-e-series,storage-management-s3-storage,console-lifecycle-planning,console-license-subscriptions,storage-management-blob-storage,console-volume-caching,data-services-disaster-recovery,storage-management-blob-storage,storage-management-google-cloud-storage,netapp-automation,data-services-ransomware-resilience,console-software-updates,console-alerts,workload-setup-admin,workload-fsx-ontap,workload-databases,workload-genai,workload-vmware
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: NetApp控制台
    url: "../console-setup-admin/index.html"
  - title: 存储管理
    url: "../storage-management-family/index.html"
  - title: 发行说明
    url: "../console-relnotes/index.html"
  - title: 备份和恢复
    url: "../data-services-backup-recovery/index.html"
  - title: 云层
    url: "../data-services-cloud-tiering/index.html"
  - title: 复制和同步
    url: "../data-services-copy-sync/index.html"
  - title: 数据分类
    url: "../data-services-data-classification/index.html"
  - title: 灾难恢复
    url: "../data-services-disaster-recovery/index.html"
  - title: 勒索软件抵御能力
    url: "../data-services-ransomware-resilience/index.html"
  - title: 复制
    url: "../data-services-replication/index.html"
  - title: 卷缓存
    url: "../data-services-volume-caching/index.html"
  - title: 工作负载
    url: "../workload-family"
